# Generated by Django 5.2.8 on 2025-12-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_alter_user_username_logincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincode',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logincode',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logincode',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='logincode',
            name='code',
            field=models.CharField(help_text='Short numeric code or token', max_length=12),
        ),
    ]
