# Generated by Django 5.2.8 on 2025-12-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aianomaly_aiprediction_aireport_parsed_aireport_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aireport',
            name='parsed',
        ),
        migrations.AlterField(
            model_name='aireport',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='aireport',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='ai_pdfs/'),
        ),
        migrations.AlterField(
            model_name='aireport',
            name='report_type',
            field=models.CharField(choices=[('sales', 'Sales'), ('stock', 'Stock'), ('anomaly', 'Anomaly')], max_length=20),
        ),
    ]
